scale_linear:
  x: -1.0
  y: 1.0
  z: 1.0
scale_angular:
  yaw: -1.0
scale_linear_turbo:
  x: -2.0
  y: 2.0
  z: 2.0
scale_angular_turbo:
  yaw: -2.0
  
axis_linear:
  x: 0
  y: 1
  z: 4
axis_angular:
  yaw: 3
  
enable_button: 5
enable_turbo_button: 4
takeoff_button: 0
land_turbo_button: 3
